name: Playwright Tests with Allure Report

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm init -y
        npm install @playwright/test allure-playwright allure-commandline --save-dev
        npx playwright install

    - name: Run Playwright tests with Allure results
      run: |
        npx playwright test --reporter=list,allure-playwright

    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
